name: Update Consonants Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecutar el script todos los días a las 8:00 UTC
  workflow_dispatch: {}  # Permitir la ejecución manual

jobs:
  update-consonants:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualizar a la última versión de actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Actualizar a la última versión de actions/setup-node
        with:
          node-version: '16'  # Mantener Node.js versión 16 por ahora

      - name: Install dependencies
        run: |
          npm install
          npm install -g npm@latest  # Actualizar npm a la última versión

      - name: Run update script
        run: node updateConsonants.js
